name: key-value-app

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env.db
    networks:
      - key-value-network
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
  mongo-db:
    image: mongodb/mongodb-community-server:7.0-ubuntu2204
    ports:
      - 27017:27017
    env_file:
      - .env.db
    environment:
      - MONGODB_HOST=db
      - PORT=3000
    volumes:
      - type: bind
        source: ./mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: mongodb-data
        target: /data/db
    networks:
      - key-value-network

volumes:
  mongodb-data:

networks:
  key-value-network: